services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bakcend
    ports:
      - "10000:10000"
    networks:
      - network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - network

networks:
  network:
    driver: bridge
